import functions_framework

from datetime import datetime
from google.cloud import storage
from google.cloud import compute_v1

from config import (
    project_id, vm_names_to_check, bucket_name,
    zip_file_ends_with, instance_name_str,
    zone, container_image, container_name,
    service_account_email,
)

# VM statuses that are considered safe to proceed past.
# TERMINATED: VM is fully stopped. SUSPENDED: VM is in a paused/hibernate state.
SAFE_STATUSES = {"TERMINATED", "SUSPENDED"}


@functions_framework.http
def trigger_data_import(request):
    """HTTP-triggered Cloud Function entry point.

    Checks whether any watched VMs are already running, then looks for a data
    file in the configured GCS bucket. If the file exists and no blocking VMs
    are active, a new VM is created to process the import.

    Args:
        request: The HTTP request object provided by the Cloud Functions framework.
            The request body is not used; all configuration comes from config.py.

    Returns:
        A tuple of (response_message, HTTP_status_code).
        - 200 with "VM created" if a VM was successfully launched.
        - 200 with an early-exit message if a blocking VM is active or no file is found.
        - 500 if the VM status check fails and it is not safe to proceed.
    """
    blocking_vm, blocking_status = get_blocking_vm_status(project_id, vm_names_to_check)

    if blocking_status == "ERROR":
        print("Could not confirm VM status due to an API error — exiting as a precaution.")
        return "Error checking VM status, exiting early", 500

    if blocking_vm is not None:
        print(f"VM '{blocking_vm}' has status '{blocking_status}' — exiting without doing anything.")
        return f"VM '{blocking_vm}' is {blocking_status}, exiting early", 200

    print("No blocking VMs found — safe to continue.")

    client = storage.Client()
    bucket = client.bucket(bucket_name)
    blobs = [b for b in bucket.list_blobs() if b.name.endswith(zip_file_ends_with)]

    if not blobs:
        print(f"No file ending with '{zip_file_ends_with}' found in bucket '{bucket_name}' — nothing to import.")
        return "No file found", 200

    print(f"Found file: {blobs[0].name} — creating VM.")
    create_vm(project_id, instance_name_str, zone, container_name, container_image, service_account_email)
    return "VM created", 200


def get_blocking_vm_status(project_id: str, vm_name_checks: list[str]) -> tuple[str | None, str | None]:
    """Check all GCP VMs for any that would block a new import job.

    Iterates over all VM instances in the project and checks whether any of
    their names contain a string from vm_name_checks. If a match is found and
    the VM is not in a safe state (TERMINATED or SUSPENDED), it is considered
    blocking.

    Args:
        project_id: The GCP project ID to search within.
        vm_name_checks: A list of substrings. Any VM whose name contains one of
            these strings will be evaluated.

    Returns:
        A tuple of (blocking_vm_name, status):
        - (None, None) if no matching VMs are found or all matches are in safe states.
        - (vm_name, status) if a VM is found in a non-safe state.
        - (None, "ERROR") if the GCP API call fails.
    """
    try:
        instance_client = compute_v1.InstancesClient()
        agg_request = compute_v1.AggregatedListInstancesRequest(project=project_id)
        agg_list = instance_client.aggregated_list(request=agg_request)

        for zone_path, response in agg_list:
            if response.instances:
                for instance in response.instances:
                    for check_str in vm_name_checks:
                        if check_str in instance.name:
                            zone_name = zone_path.split("/")[-1]
                            print(f"Found VM: {instance.name} in {zone_name} with status: {instance.status}")
                            if instance.status not in SAFE_STATUSES:
                                return instance.name, instance.status

        print("No blocking VMs found.")
        return None, None

    except Exception as e:
        print(f"Error checking VM status: {e}")
        return None, "ERROR"


def create_vm(
    in_project_id: str,
    instance_name_str: str,
    zone: str,
    container_name: str,
    container_image_path: str,
    service_account_email: str,
):
    """Create a GCE VM that pulls and runs a container image on startup.

    The VM uses Container-Optimized OS and runs a Docker container via a
    startup script. The VM name is generated by appending a UTC timestamp to
    instance_name_str to keep each run uniquely identifiable.

    Args:
        in_project_id: The GCP project ID in which to create the VM.
        instance_name_str: A prefix for the VM name. A timestamp is appended
            automatically (e.g. "data-etl-20240318-120000").
        zone: The GCP zone to create the VM in (e.g. "us-central1-b").
        container_name: The name to assign to the Docker container.
        container_image_path: The full Artifact Registry path to the container image.
        service_account_email: Email of the service account the VM will run as.
    """
    instance_name = f"{instance_name_str}-{datetime.now().strftime('%Y%m%d-%H%M%S')}"

    instance_client = compute_v1.InstancesClient()

    machine_type = f"zones/{zone}/machineTypes/n2-standard-8"
    source_image = "projects/cos-cloud/global/images/family/cos-stable"

    boot_disk = compute_v1.AttachedDisk(
        auto_delete=True,
        boot=True,
        initialize_params=compute_v1.AttachedDiskInitializeParams(
            source_image=source_image,
            disk_size_gb=150,
            disk_type=f"zones/{zone}/diskTypes/pd-ssd",
        ),
    )

    network_interface = compute_v1.NetworkInterface(
        network="global/networks/default",
        access_configs=[
            compute_v1.AccessConfig(
                name="External NAT",
                type_="ONE_TO_ONE_NAT",
            )
        ],
    )

    startup_script = f"""#!/bin/bash
export HOME=/home/appuser
mkdir -p $HOME/.docker

docker-credential-gcr configure-docker --registries=us-central1-docker.pkg.dev

docker pull {container_image_path}
docker run --name {container_name} {container_image_path}
"""

    instance = compute_v1.Instance(
        name=instance_name,
        machine_type=machine_type,
        disks=[boot_disk],
        network_interfaces=[network_interface],
        service_accounts=[
            compute_v1.ServiceAccount(
                email=service_account_email,
                scopes=["https://www.googleapis.com/auth/cloud-platform"],
            )
        ],
        metadata=compute_v1.Metadata(
            items=[
                compute_v1.Items(key="startup-script", value=startup_script)
            ]
        ),
        scheduling=compute_v1.Scheduling(
            automatic_restart=False,
            on_host_maintenance="TERMINATE",
            preemptible=False,
        ),
        deletion_protection=False,
    )

    insert_request = compute_v1.InsertInstanceRequest(
        project=in_project_id,
        zone=zone,
        instance_resource=instance,
    )

    print(f"Creating VM: {instance_name} in zone {zone}")
    operation = instance_client.insert(request=insert_request)
    print(f"VM creation initiated: {instance_name}")
    print(f"Operation: {operation.name}")
